### PR TITLE
Feature map site

### PR DESCRIPTION
**Pull request by rammazzoti2000**
This branch is used for code review.
It is built only of html and css using float positioning.

It contains a top navigation bar with the main logo, main icon functions like search ad menu, as well as subscribe and login buttons.

It has a main header picture with caption and under, a social interaction section.

The main article section it contains the article with aside section, embedded video and image with caption and a theory of inflation section built with grid display property (was very hard to understand the logic).

The last part is made up of a kind of comment section with social sharing section.
Right under it has extra content containing main extra content on the left and on the right most popular readings, last but not least the footer

### CODE REVIEW

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
## Hi Team   
#### Great Job so far, but there are few more things required. 

## General

- [x] Check HTML markup with this validator https://validator.w3.org/#validate_by_upload.

- [x] Please let's fix the footer links that are missing in the project.
### Your Version

### Original Version



### Make changes and submit another code review request.
*Happy coding*

**Comment by rammazzoti2000** [comment]
@kobiyoyo Hey thank for review, aren't those in html only warnings and not actual errors?
Also from the last review of [this branch](https://github.com/rammazzoti2000/Positioning-and-Floating-Elements/pull/4) the footer wasn't mentioned only the expand thing.
Do you also have an email or some sort of communication in case I need to talk to you?

**Comment by rammazzoti2000** [comment]
Hello @kobiyoyo take a look now and let me know please
Screenshot from 2020-01-24 03-36-40

**Comment by euqueme** [comment]
> ### Pull Request under the review by Maria Eugenia Quemé P. (TSE)

## Hello @rammazzoti2000  and @vzdrizhni  :bulb:
### Awesome job doing the changes requested by the previous reviewer :medal_sports:  your page looks amazing :art: :eyes:

### I just have one change for you but it's pretty much optional:

[OPTIONAL] The navbar in the original page has a light gray border-button I encourage you to add this change to your page

**Yours**
image

**Original**
image

### That's it. make this change and submit the project no need to request for a code review :rocket:

#### STATUS OF THE PROJECT: APPROVED :green_apple:

**Comment by rammazzoti2000** [comment]
@euqueme thank you for the suggestion, in fact it looks better

**Pull request merged**
