### PR TITLE
Feature branch

### PR DESCRIPTION
**Pull request by rammazzoti2000**
This branch is used for code review.
It is built only of  html and css using grid and flexbox display properties.

It contains a top navigation bar with the main logo, main icon functions like search ad menu, as well as subscribe and login buttons.

It has a main header picture with caption and under, a social interaction section.

The main article section it contains the article with aside section, embedded video and image with caption and a theory of inflation section built with grid display property (was very hard to understand the logic).

The last part is made up of a kind of comment section with social sharing section.
Right under it has extra content containing main extra content on the left and on the right most popular readings, last but not least the footer

### CODE REVIEW

**Review by mosesogwo — CHANGES_REQUESTED** [review]
**HI team, :clap:You have done a good job. We have a few required changes:**
1. Your page should have this fixed footer that sticks at the bottom (check original page):
image

2. Validate your html markup [here](https://validator.w3.org/#validate_by_upload) as instructed on pathwright.



3. Project requirements states that you should align all items with float. You have used grid and flex.



Kindly make these changes and submit another code review request.

**Happy coding :smile:**

**Status: Changes requested**

**Comment by rammazzoti2000** [comment]
I wonder if the content of  theory of inflation section can be left in display grid, and for the container use float property?
Screenshot from 2020-01-22 11-53-03

**Comment by mosesogwo** [comment]
Hi @rammazzoti2000, @vzdrizhni 

Please you can go ahead and use grid for the theory of inflation section only. Float, grid and flex are all meant to achieve the same thing but this project is targeted at teaching you how to use float, that is why you have that requirement.

If you use float for alignment in other sections of the page, you can use grid only for the theory of inflation section as you are asking.

Happy coding:smile:

**Comment by rammazzoti2000** [comment]
Hello @mosesogwo I closed this branch because I switched my work to a new branch `feature-map-site`. 
Already made a request for that new branch, please have a look and let me know if it passed.

**Pull request closed without merging**
